<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InsurerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupedEntityRepository extends EntityRepository
{
    public function getAllNonGroupedQb()
    {
        return $this->createQueryBuilder('ge')
            ->leftJoin('ge.groupedEntityAsParent', 'goe')
            ->andWhere('goe.groupedEntityAsChild IS NULL')
            ->andWhere('ge.parentMagnet IS NULL')
        ;
    }
}